### ISSUE TITLE
Implement script to generate image from saved latents

### ISSUE THREAD

**Issue by gatheluck** [Hina39/HyperInverter#9]
## Why

#6 でlatentをnpzファイルとして保存するスクリプトを作成しました. しかし, latentが正しく保存されているか確認は出来ていません. このIssueではnpzからlatentsを読み出して,  画像を生成するスクリプトを実装します. これによってlatentが正しく保存されていることを確認します. 

## Definition of Done

- `scripts/save_latent.py` によって保存された, npzファイルからlatentの情報を読み込んで, 画像を生成するスクリプト `scripts/generate_from_latent.py` を実装する.

## How

`scripts/inference.py` の後半をほぼそのままパクればよい.

**Comment by Hina39** [comment]
owattayo^^
